CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Cities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "LocalizedName" character varying(50) NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("Id")
);

CREATE TABLE "CollaborationGoals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "LocalizedName" character varying(50) NOT NULL,
    CONSTRAINT "PK_CollaborationGoals" PRIMARY KEY ("Id")
);

CREATE TABLE "EmailVerificationCodes" (
    "Id" uuid NOT NULL,
    "Email" text NOT NULL,
    "Code" character varying(6) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    CONSTRAINT "PK_EmailVerificationCodes" PRIMARY KEY ("Id")
);

CREATE TABLE "Genres" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "LocalizedName" character varying(50) NOT NULL,
    CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
);

CREATE TABLE "MusicalSpecializations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "LocalizedName" character varying(50) NOT NULL,
    CONSTRAINT "PK_MusicalSpecializations" PRIMARY KEY ("Id")
);

CREATE TABLE "MusicianProfiles" (
    "Id" uuid NOT NULL,
    "FullName" character varying(100) NOT NULL,
    "Avatar" bytea,
    "Age" integer,
    "Description" character varying(500),
    "Phone" text,
    "Telegram" character varying(50),
    "CityId" integer NOT NULL,
    "Experience" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_MusicianProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MusicianProfiles_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CollaborationSuggestions" (
    "Id" uuid NOT NULL,
    "FromProfileId" uuid NOT NULL,
    "ToProfileId" uuid NOT NULL,
    "Message" character varying(500),
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CollaborationSuggestions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CollaborationSuggestions_MusicianProfiles_FromProfileId" FOREIGN KEY ("FromProfileId") REFERENCES "MusicianProfiles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CollaborationSuggestions_MusicianProfiles_ToProfileId" FOREIGN KEY ("ToProfileId") REFERENCES "MusicianProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PortfolioAudio" (
    "Id" uuid NOT NULL,
    "ProfileId" uuid NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(500),
    "FileData" bytea NOT NULL,
    "MimeType" character varying(50) NOT NULL,
    "Duration" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PortfolioAudio" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PortfolioAudio_MusicianProfiles_ProfileId" FOREIGN KEY ("ProfileId") REFERENCES "MusicianProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PortfolioPhotos" (
    "Id" uuid NOT NULL,
    "ProfileId" uuid NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(500),
    "FileData" bytea NOT NULL,
    "MimeType" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PortfolioPhotos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PortfolioPhotos_MusicianProfiles_ProfileId" FOREIGN KEY ("ProfileId") REFERENCES "MusicianProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PortfolioVideo" (
    "Id" uuid NOT NULL,
    "ProfileId" uuid NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(500),
    "FileData" bytea NOT NULL,
    "MimeType" character varying(50) NOT NULL,
    "Duration" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PortfolioVideo" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PortfolioVideo_MusicianProfiles_ProfileId" FOREIGN KEY ("ProfileId") REFERENCES "MusicianProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProfileCollaborationGoal" (
    "CollaborationGoalsId" integer NOT NULL,
    "ProfilesId" uuid NOT NULL,
    CONSTRAINT "PK_ProfileCollaborationGoal" PRIMARY KEY ("CollaborationGoalsId", "ProfilesId"),
    CONSTRAINT "FK_ProfileCollaborationGoal_CollaborationGoals_CollaborationGo~" FOREIGN KEY ("CollaborationGoalsId") REFERENCES "CollaborationGoals" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProfileCollaborationGoal_MusicianProfiles_ProfilesId" FOREIGN KEY ("ProfilesId") REFERENCES "MusicianProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProfileGenre" (
    "GenresId" integer NOT NULL,
    "ProfilesId" uuid NOT NULL,
    CONSTRAINT "PK_ProfileGenre" PRIMARY KEY ("GenresId", "ProfilesId"),
    CONSTRAINT "FK_ProfileGenre_Genres_GenresId" FOREIGN KEY ("GenresId") REFERENCES "Genres" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProfileGenre_MusicianProfiles_ProfilesId" FOREIGN KEY ("ProfilesId") REFERENCES "MusicianProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProfileSpecialty" (
    "ProfilesId" uuid NOT NULL,
    "SpecialtiesId" integer NOT NULL,
    CONSTRAINT "PK_ProfileSpecialty" PRIMARY KEY ("ProfilesId", "SpecialtiesId"),
    CONSTRAINT "FK_ProfileSpecialty_MusicalSpecializations_SpecialtiesId" FOREIGN KEY ("SpecialtiesId") REFERENCES "MusicalSpecializations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProfileSpecialty_MusicianProfiles_ProfilesId" FOREIGN KEY ("ProfilesId") REFERENCES "MusicianProfiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Email" text NOT NULL,
    "ProfileCreated" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "FavoriteProfileIds" uuid[] NOT NULL,
    "MusicianProfileId" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_MusicianProfiles_MusicianProfileId" FOREIGN KEY ("MusicianProfileId") REFERENCES "MusicianProfiles" ("Id")
);

INSERT INTO "Cities" ("Id", "LocalizedName", "Name")
VALUES (1, 'Москва', 'Moscow');
INSERT INTO "Cities" ("Id", "LocalizedName", "Name")
VALUES (2, 'Санкт-Петербург', 'Saint Petersburg');
INSERT INTO "Cities" ("Id", "LocalizedName", "Name")
VALUES (3, 'Новосибирск', 'Novosibirsk');
INSERT INTO "Cities" ("Id", "LocalizedName", "Name")
VALUES (4, 'Екатеринбург', 'Yekaterinburg');
INSERT INTO "Cities" ("Id", "LocalizedName", "Name")
VALUES (5, 'Казань', 'Kazan');

INSERT INTO "CollaborationGoals" ("Id", "LocalizedName", "Name")
VALUES (1, 'Ищу участников в группу', 'band');
INSERT INTO "CollaborationGoals" ("Id", "LocalizedName", "Name")
VALUES (2, 'Готов(а) к сессионной работе', 'session');
INSERT INTO "CollaborationGoals" ("Id", "LocalizedName", "Name")
VALUES (3, 'Открыт(а) к совместным проектам', 'collaboration');
INSERT INTO "CollaborationGoals" ("Id", "LocalizedName", "Name")
VALUES (4, 'Ищу продюсера', 'producer');
INSERT INTO "CollaborationGoals" ("Id", "LocalizedName", "Name")
VALUES (5, 'Ищу исполнителя для песен', 'artist');

INSERT INTO "Genres" ("Id", "LocalizedName", "Name")
VALUES (1, 'Джаз', 'jazz');
INSERT INTO "Genres" ("Id", "LocalizedName", "Name")
VALUES (2, 'Рок', 'rock');
INSERT INTO "Genres" ("Id", "LocalizedName", "Name")
VALUES (3, 'Классика', 'classical');
INSERT INTO "Genres" ("Id", "LocalizedName", "Name")
VALUES (4, 'Электроника', 'electronic');
INSERT INTO "Genres" ("Id", "LocalizedName", "Name")
VALUES (5, 'Поп', 'pop');
INSERT INTO "Genres" ("Id", "LocalizedName", "Name")
VALUES (6, 'Хип-хоп', 'hip-hop');
INSERT INTO "Genres" ("Id", "LocalizedName", "Name")
VALUES (7, 'Метал', 'metal');
INSERT INTO "Genres" ("Id", "LocalizedName", "Name")
VALUES (8, 'Блюз', 'blues');

INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (1, 'Вокалист', 'vocalist');
INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (2, 'Гитарист', 'guitarist');
INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (3, 'Бас-гитарист', 'bassist');
INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (4, 'Ударник', 'drummer');
INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (5, 'Клавишник', 'keyboardist');
INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (6, 'Композитор', 'composer');
INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (7, 'Продюсер', 'producer');
INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (8, 'Звукорежиссёр', 'sound-engineer');
INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (9, 'Диджей', 'dj');
INSERT INTO "MusicalSpecializations" ("Id", "LocalizedName", "Name")
VALUES (10, 'Скрипач', 'violinist');

CREATE INDEX "IX_CollaborationSuggestions_FromProfileId" ON "CollaborationSuggestions" ("FromProfileId");

CREATE INDEX "IX_CollaborationSuggestions_ToProfileId" ON "CollaborationSuggestions" ("ToProfileId");

CREATE INDEX "IX_MusicianProfiles_CityId" ON "MusicianProfiles" ("CityId");

CREATE INDEX "IX_PortfolioAudio_ProfileId" ON "PortfolioAudio" ("ProfileId");

CREATE INDEX "IX_PortfolioPhotos_ProfileId" ON "PortfolioPhotos" ("ProfileId");

CREATE INDEX "IX_PortfolioVideo_ProfileId" ON "PortfolioVideo" ("ProfileId");

CREATE INDEX "IX_ProfileCollaborationGoal_ProfilesId" ON "ProfileCollaborationGoal" ("ProfilesId");

CREATE INDEX "IX_ProfileGenre_ProfilesId" ON "ProfileGenre" ("ProfilesId");

CREATE INDEX "IX_ProfileSpecialty_SpecialtiesId" ON "ProfileSpecialty" ("SpecialtiesId");

CREATE INDEX "IX_Users_MusicianProfileId" ON "Users" ("MusicianProfileId");

SELECT setval(
    pg_get_serial_sequence('"Cities"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Cities") + 1,
        nextval(pg_get_serial_sequence('"Cities"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"CollaborationGoals"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "CollaborationGoals") + 1,
        nextval(pg_get_serial_sequence('"CollaborationGoals"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Genres"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Genres") + 1,
        nextval(pg_get_serial_sequence('"Genres"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"MusicalSpecializations"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "MusicalSpecializations") + 1,
        nextval(pg_get_serial_sequence('"MusicalSpecializations"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251228173847_InitialCreate', '8.0.22');

COMMIT;

