// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicianFinder.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicianFinder.Infrastructure.Migrations
{
    [DbContext(typeof(MusicianFinderDbContext))]
    partial class MusicianFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CollaborationGoalMusicianProfile", b =>
                {
                    b.Property<int>("CollaborationGoalsId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("CollaborationGoalsId", "ProfilesId");

                    b.HasIndex("ProfilesId");

                    b.ToTable("ProfileCollaborationGoals", (string)null);
                });

            modelBuilder.Entity("GenreMusicianProfile", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("GenresId", "ProfilesId");

                    b.HasIndex("ProfilesId");

                    b.ToTable("ProfileGenres", (string)null);
                });

            modelBuilder.Entity("GenreMusicianProfile1", b =>
                {
                    b.Property<int>("DesiredGenresId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfilesLookingForThisGenreId")
                        .HasColumnType("uuid");

                    b.HasKey("DesiredGenresId", "ProfilesLookingForThisGenreId");

                    b.HasIndex("ProfilesLookingForThisGenreId");

                    b.ToTable("ProfileDesiredGenres", (string)null);
                });

            modelBuilder.Entity("MusicalSpecialtyMusicianProfile", b =>
                {
                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecialtiesId")
                        .HasColumnType("integer");

                    b.HasKey("ProfilesId", "SpecialtiesId");

                    b.HasIndex("SpecialtiesId");

                    b.ToTable("ProfileSpecialties", (string)null);
                });

            modelBuilder.Entity("MusicalSpecialtyMusicianProfile1", b =>
                {
                    b.Property<int>("DesiredSpecialtiesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfilesLookingForThisSpecialtyId")
                        .HasColumnType("uuid");

                    b.HasKey("DesiredSpecialtiesId", "ProfilesLookingForThisSpecialtyId");

                    b.HasIndex("ProfilesLookingForThisSpecialtyId");

                    b.ToTable("ProfileDesiredSpecialties", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("City", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Москва",
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Санкт-Петербург",
                            Name = "Saint Petersburg"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Новосибирск",
                            Name = "Novosibirsk"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Екатеринбург",
                            Name = "Yekaterinburg"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Казань",
                            Name = "Kazan"
                        });
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.CollaborationGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CollaborationGoal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Ищу участников в группу",
                            Name = "band"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Готов(а) к сессионной работе",
                            Name = "session"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Открыт(а) к совместным проектам",
                            Name = "collaboration"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Ищу продюсера",
                            Name = "producer"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Ищу исполнителя для песен",
                            Name = "artist"
                        });
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.CollaborationSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FromProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ToProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("FromProfileId");

                    b.HasIndex("ToProfileId");

                    b.ToTable("CollaborationSuggestion", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.EmailVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Code", "IsUsed");

                    b.ToTable("EmailVerificationCode", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatorProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Scheduled");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("RegionId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.EventRegistration", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("EventId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("EventId", "ProfileId")
                        .IsUnique();

                    b.ToTable("EventRegistration", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Genre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Джаз",
                            Name = "jazz"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Рок",
                            Name = "rock"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Классика",
                            Name = "classical"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Электроника",
                            Name = "electronic"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Поп",
                            Name = "pop"
                        },
                        new
                        {
                            Id = 6,
                            LocalizedName = "Хип-хоп",
                            Name = "hip-hop"
                        },
                        new
                        {
                            Id = 7,
                            LocalizedName = "Метал",
                            Name = "metal"
                        },
                        new
                        {
                            Id = 8,
                            LocalizedName = "Блюз",
                            Name = "blues"
                        });
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.MusicalSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("MusicalSpecialty", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Вокалист",
                            Name = "vocalist"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Гитарист",
                            Name = "guitarist"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Бас-гитарист",
                            Name = "bassist"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Ударник",
                            Name = "drummer"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Клавишник",
                            Name = "keyboardist"
                        },
                        new
                        {
                            Id = 6,
                            LocalizedName = "Композитор",
                            Name = "composer"
                        },
                        new
                        {
                            Id = 7,
                            LocalizedName = "Продюсер",
                            Name = "producer"
                        },
                        new
                        {
                            Id = 8,
                            LocalizedName = "Звукорежиссёр",
                            Name = "sound-engineer"
                        },
                        new
                        {
                            Id = 9,
                            LocalizedName = "Диджей",
                            Name = "dj"
                        },
                        new
                        {
                            Id = 10,
                            LocalizedName = "Скрипач",
                            Name = "violinist"
                        });
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.MusicianProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LookingFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotifyByEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotifyByVk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telegram")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VkUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("MusicianProfile", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.PortfolioAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PortfolioAudio", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.PortfolioPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PortfolioPhoto", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.PortfolioVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PortfolioVideo", (string)null);
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Region", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Московская область",
                            Name = "Moscow Oblast"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Ленинградская область",
                            Name = "Leningrad Oblast"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Новосибирская область",
                            Name = "Novosibirsk Oblast"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Свердловская область",
                            Name = "Sverdlovsk Oblast"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Татарстан",
                            Name = "Tatarstan"
                        });
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProfileCreated")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("User");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("CollaborationGoalMusicianProfile", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.CollaborationGoal", null)
                        .WithMany()
                        .HasForeignKey("CollaborationGoalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreMusicianProfile", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreMusicianProfile1", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("DesiredGenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesLookingForThisGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicalSpecialtyMusicianProfile", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.MusicalSpecialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicalSpecialtyMusicianProfile1", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.MusicalSpecialty", null)
                        .WithMany()
                        .HasForeignKey("DesiredSpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesLookingForThisSpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.CollaborationSuggestion", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", "FromProfile")
                        .WithMany()
                        .HasForeignKey("FromProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", "ToProfile")
                        .WithMany()
                        .HasForeignKey("ToProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromProfile");

                    b.Navigation("ToProfile");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.Event", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", "CreatorProfile")
                        .WithMany()
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("CreatorProfile");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.EventRegistration", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.MusicianProfile", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicianFinder.Domain.Entities.User", null)
                        .WithOne("MusicianProfile")
                        .HasForeignKey("MusicianFinder.Domain.Entities.MusicianProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.PortfolioAudio", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", "Profile")
                        .WithMany("AudioFiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.PortfolioPhoto", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", "Profile")
                        .WithMany("Photos")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.PortfolioVideo", b =>
                {
                    b.HasOne("MusicianFinder.Domain.Entities.MusicianProfile", "Profile")
                        .WithMany("VideoFiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.MusicianProfile", b =>
                {
                    b.Navigation("AudioFiles");

                    b.Navigation("Photos");

                    b.Navigation("VideoFiles");
                });

            modelBuilder.Entity("MusicianFinder.Domain.Entities.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("MusicianProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
