// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MusicianFinderDbContext))]
    partial class MusicianFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.MusicianProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("Instruments")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("LookingFor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("MusicianProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Bio = "Jazz vocalist looking for a band",
                            City = "Moscow",
                            FullName = "Alice Johnson",
                            Genres = new[] { "jazz", "soul" },
                            Instruments = new[] { "vocals" },
                            LookingFor = "band"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Bio = "Guitarist, session musician",
                            City = "Saint Petersburg",
                            FullName = "Bob Smith",
                            Genres = new[] { "rock", "blues" },
                            Instruments = new[] { "guitar", "bass" },
                            LookingFor = "session"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Bio = "Pianist and composer",
                            City = "Novosibirsk",
                            FullName = "Clara Davis",
                            Genres = new[] { "classical", "electronic" },
                            Instruments = new[] { "piano", "synthesizer" },
                            LookingFor = "collaboration"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
