// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MusicianFinderDbContext))]
    partial class MusicianFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PortfolioPhotos");
                });

            modelBuilder.Entity("ProfileCollaborationGoal", b =>
                {
                    b.Property<int>("CollaborationGoalsId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("CollaborationGoalsId", "ProfilesId");

                    b.HasIndex("ProfilesId");

                    b.ToTable("ProfileCollaborationGoal");

                    b.HasData(
                        new
                        {
                            CollaborationGoalsId = 1,
                            ProfilesId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            CollaborationGoalsId = 3,
                            ProfilesId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            CollaborationGoalsId = 2,
                            ProfilesId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("ProfileGenre", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("GenresId", "ProfilesId");

                    b.HasIndex("ProfilesId");

                    b.ToTable("ProfileGenre");

                    b.HasData(
                        new
                        {
                            GenresId = 2,
                            ProfilesId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            GenresId = 1,
                            ProfilesId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            GenresId = 2,
                            ProfilesId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("ProfileSpecialty", b =>
                {
                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecialtiesId")
                        .HasColumnType("integer");

                    b.HasKey("ProfilesId", "SpecialtiesId");

                    b.HasIndex("SpecialtiesId");

                    b.ToTable("ProfileSpecialty");

                    b.HasData(
                        new
                        {
                            ProfilesId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SpecialtiesId = 2
                        },
                        new
                        {
                            ProfilesId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SpecialtiesId = 1
                        },
                        new
                        {
                            ProfilesId = new Guid("66666666-6666-6666-6666-666666666666"),
                            SpecialtiesId = 3
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Москва",
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Санкт-Петербург",
                            Name = "Saint Petersburg"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Новосибирск",
                            Name = "Novosibirsk"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Екатеринбург",
                            Name = "Yekaterinburg"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Казань",
                            Name = "Kazan"
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.CollaborationGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CollaborationGoals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Ищу участников в группу",
                            Name = "band"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Готов(а) к сессионной работе",
                            Name = "session"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Открыт(а) к совместным проектам",
                            Name = "collaboration"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Ищу продюсера",
                            Name = "producer"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Ищу исполнителя для песен",
                            Name = "artist"
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.CollaborationSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("CollaborationSuggestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 12, 24, 18, 48, 10, 371, DateTimeKind.Utc).AddTicks(9395),
                            FromUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Message = "Привет! Слушал твои записи — классный голос. Хочу пригласить в новый проект.",
                            Status = "pending",
                            ToUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 12, 24, 18, 48, 10, 371, DateTimeKind.Utc).AddTicks(9396)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 12, 24, 18, 49, 10, 371, DateTimeKind.Utc).AddTicks(9400),
                            FromUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Message = "Спасибо! Давай обсудим детали.",
                            Status = "accepted",
                            ToUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2025, 12, 24, 18, 49, 10, 371, DateTimeKind.Utc).AddTicks(9401)
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.EmailVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("backend.Models.Classes.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Джаз",
                            Name = "jazz"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Рок",
                            Name = "rock"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Классика",
                            Name = "classical"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Электроника",
                            Name = "electronic"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Поп",
                            Name = "pop"
                        },
                        new
                        {
                            Id = 6,
                            LocalizedName = "Хип-хоп",
                            Name = "hip-hop"
                        },
                        new
                        {
                            Id = 7,
                            LocalizedName = "Метал",
                            Name = "metal"
                        },
                        new
                        {
                            Id = 8,
                            LocalizedName = "Блюз",
                            Name = "blues"
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.MusicalSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("MusicalSpecializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Вокалист",
                            Name = "vocalist"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Гитарист",
                            Name = "guitarist"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Бас-гитарист",
                            Name = "bassist"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Ударник",
                            Name = "drummer"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Клавишник",
                            Name = "keyboardist"
                        },
                        new
                        {
                            Id = 6,
                            LocalizedName = "Композитор",
                            Name = "composer"
                        },
                        new
                        {
                            Id = 7,
                            LocalizedName = "Продюсер",
                            Name = "producer"
                        },
                        new
                        {
                            Id = 8,
                            LocalizedName = "Звукорежиссёр",
                            Name = "sound-engineer"
                        },
                        new
                        {
                            Id = 9,
                            LocalizedName = "Диджей",
                            Name = "dj"
                        },
                        new
                        {
                            Id = 10,
                            LocalizedName = "Скрипач",
                            Name = "violinist"
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.MusicianProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Telegram")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MusicianProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Age = 28,
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 12, 24, 18, 43, 10, 371, DateTimeKind.Utc).AddTicks(9266),
                            Description = "Профессиональный гитарист, ищу группу для выступлений.",
                            Experience = 7,
                            FullName = "Алексей Иванов",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 12, 24, 18, 43, 10, 371, DateTimeKind.Utc).AddTicks(9267),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Age = 25,
                            CityId = 2,
                            CreatedAt = new DateTime(2025, 12, 24, 18, 44, 10, 371, DateTimeKind.Utc).AddTicks(9271),
                            Description = "Вокалистка, участвую в джазовых проектах.",
                            Experience = 5,
                            FullName = "Мария Петрова",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 12, 24, 18, 44, 10, 371, DateTimeKind.Utc).AddTicks(9272),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Age = 30,
                            CityId = 3,
                            CreatedAt = new DateTime(2025, 12, 24, 18, 45, 10, 371, DateTimeKind.Utc).AddTicks(9277),
                            Description = "Бас-гитарист, открыт к совместным проектам.",
                            Experience = 10,
                            FullName = "Иван Сидоров",
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2025, 12, 24, 18, 45, 10, 371, DateTimeKind.Utc).AddTicks(9277),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PortfolioAudio");
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PortfolioVideo");
                });

            modelBuilder.Entity("backend.Models.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("FavoriteProfileIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProfileCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 24, 18, 43, 10, 371, DateTimeKind.Utc).AddTicks(9170),
                            Email = "user1@example.com",
                            FavoriteProfileIds = new List<Guid> { new Guid("33333333-3333-3333-3333-333333333333") },
                            FullName = "Алексей Иванов",
                            IsDeleted = false,
                            ProfileCompleted = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 24, 18, 44, 10, 371, DateTimeKind.Utc).AddTicks(9183),
                            Email = "user2@example.com",
                            FavoriteProfileIds = new List<Guid> { new Guid("44444444-4444-4444-4444-444444444444") },
                            FullName = "Мария Петрова",
                            IsDeleted = false,
                            ProfileCompleted = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 24, 18, 45, 10, 371, DateTimeKind.Utc).AddTicks(9186),
                            Email = "user3@example.com",
                            FavoriteProfileIds = new List<Guid>(),
                            FullName = "Иван Сидоров",
                            IsDeleted = false,
                            ProfileCompleted = true
                        });
                });

            modelBuilder.Entity("PortfolioPhoto", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", "Profile")
                        .WithMany("Photos")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ProfileCollaborationGoal", b =>
                {
                    b.HasOne("backend.Models.Classes.CollaborationGoal", null)
                        .WithMany()
                        .HasForeignKey("CollaborationGoalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Classes.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfileGenre", b =>
                {
                    b.HasOne("backend.Models.Classes.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Classes.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfileSpecialty", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Classes.MusicalSpecialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Classes.CollaborationSuggestion", b =>
                {
                    b.HasOne("backend.Models.Classes.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Classes.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("backend.Models.Classes.MusicianProfile", b =>
                {
                    b.HasOne("backend.Models.Classes.City", "City")
                        .WithMany("Profiles")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Classes.User", "User")
                        .WithOne("MusicianProfile")
                        .HasForeignKey("backend.Models.Classes.MusicianProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioAudio", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", "Profile")
                        .WithMany("AudioFiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioVideo", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", "Profile")
                        .WithMany("VideoFiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("backend.Models.Classes.City", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("backend.Models.Classes.MusicianProfile", b =>
                {
                    b.Navigation("AudioFiles");

                    b.Navigation("Photos");

                    b.Navigation("VideoFiles");
                });

            modelBuilder.Entity("backend.Models.Classes.User", b =>
                {
                    b.Navigation("MusicianProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
