// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MusicianFinderDbContext))]
    partial class MusicianFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfileCollaborationGoal", b =>
                {
                    b.Property<int>("CollaborationGoalsId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("CollaborationGoalsId", "ProfilesId");

                    b.HasIndex("ProfilesId");

                    b.ToTable("ProfileCollaborationGoal");
                });

            modelBuilder.Entity("ProfileGenre", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid");

                    b.HasKey("GenresId", "ProfilesId");

                    b.HasIndex("ProfilesId");

                    b.ToTable("ProfileGenre");
                });

            modelBuilder.Entity("ProfileSpecialty", b =>
                {
                    b.Property<Guid>("ProfilesId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecialtiesId")
                        .HasColumnType("integer");

                    b.HasKey("ProfilesId", "SpecialtiesId");

                    b.HasIndex("SpecialtiesId");

                    b.ToTable("ProfileSpecialty");
                });

            modelBuilder.Entity("backend.Models.Classes.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Москва",
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Санкт-Петербург",
                            Name = "Saint Petersburg"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Новосибирск",
                            Name = "Novosibirsk"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Екатеринбург",
                            Name = "Yekaterinburg"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Казань",
                            Name = "Kazan"
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.CollaborationGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CollaborationGoals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Ищу участников в группу",
                            Name = "band"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Готов(а) к сессионной работе",
                            Name = "session"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Открыт(а) к совместным проектам",
                            Name = "collaboration"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Ищу продюсера",
                            Name = "producer"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Ищу исполнителя для песен",
                            Name = "artist"
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.CollaborationSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromProfileId");

                    b.HasIndex("ToProfileId");

                    b.ToTable("CollaborationSuggestions");
                });

            modelBuilder.Entity("backend.Models.Classes.EmailVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("backend.Models.Classes.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Джаз",
                            Name = "jazz"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Рок",
                            Name = "rock"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Классика",
                            Name = "classical"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Электроника",
                            Name = "electronic"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Поп",
                            Name = "pop"
                        },
                        new
                        {
                            Id = 6,
                            LocalizedName = "Хип-хоп",
                            Name = "hip-hop"
                        },
                        new
                        {
                            Id = 7,
                            LocalizedName = "Метал",
                            Name = "metal"
                        },
                        new
                        {
                            Id = 8,
                            LocalizedName = "Блюз",
                            Name = "blues"
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.MusicalSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("MusicalSpecializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalizedName = "Вокалист",
                            Name = "vocalist"
                        },
                        new
                        {
                            Id = 2,
                            LocalizedName = "Гитарист",
                            Name = "guitarist"
                        },
                        new
                        {
                            Id = 3,
                            LocalizedName = "Бас-гитарист",
                            Name = "bassist"
                        },
                        new
                        {
                            Id = 4,
                            LocalizedName = "Ударник",
                            Name = "drummer"
                        },
                        new
                        {
                            Id = 5,
                            LocalizedName = "Клавишник",
                            Name = "keyboardist"
                        },
                        new
                        {
                            Id = 6,
                            LocalizedName = "Композитор",
                            Name = "composer"
                        },
                        new
                        {
                            Id = 7,
                            LocalizedName = "Продюсер",
                            Name = "producer"
                        },
                        new
                        {
                            Id = 8,
                            LocalizedName = "Звукорежиссёр",
                            Name = "sound-engineer"
                        },
                        new
                        {
                            Id = 9,
                            LocalizedName = "Диджей",
                            Name = "dj"
                        },
                        new
                        {
                            Id = 10,
                            LocalizedName = "Скрипач",
                            Name = "violinist"
                        });
                });

            modelBuilder.Entity("backend.Models.Classes.MusicianProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Telegram")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("MusicianProfiles");
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PortfolioAudio");
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PortfolioPhotos");
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PortfolioVideo");
                });

            modelBuilder.Entity("backend.Models.Classes.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("FavoriteProfileIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MusicianProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ProfileCreated")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MusicianProfileId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProfileCollaborationGoal", b =>
                {
                    b.HasOne("backend.Models.Classes.CollaborationGoal", null)
                        .WithMany()
                        .HasForeignKey("CollaborationGoalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Classes.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfileGenre", b =>
                {
                    b.HasOne("backend.Models.Classes.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Classes.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfileSpecialty", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Classes.MusicalSpecialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Classes.CollaborationSuggestion", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", "FromProfile")
                        .WithMany()
                        .HasForeignKey("FromProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Classes.MusicianProfile", "ToProfile")
                        .WithMany()
                        .HasForeignKey("ToProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromProfile");

                    b.Navigation("ToProfile");
                });

            modelBuilder.Entity("backend.Models.Classes.MusicianProfile", b =>
                {
                    b.HasOne("backend.Models.Classes.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioAudio", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", "Profile")
                        .WithMany("AudioFiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioPhoto", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", "Profile")
                        .WithMany("Photos")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("backend.Models.Classes.PortfolioVideo", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", "Profile")
                        .WithMany("VideoFiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("backend.Models.Classes.User", b =>
                {
                    b.HasOne("backend.Models.Classes.MusicianProfile", "MusicianProfile")
                        .WithMany()
                        .HasForeignKey("MusicianProfileId");

                    b.Navigation("MusicianProfile");
                });

            modelBuilder.Entity("backend.Models.Classes.MusicianProfile", b =>
                {
                    b.Navigation("AudioFiles");

                    b.Navigation("Photos");

                    b.Navigation("VideoFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
