using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MusicianFinder.Domain.Entities;

namespace MusicianFinder.Infrastructure.Persistence.Configurations
{
    /// <summary>
    /// Конфигурация сущности <see cref="City"/>.
    /// </summary>
    public class CityConfiguration : IEntityTypeConfiguration<City>
    {
        /// <inheritdoc />
        public void Configure(EntityTypeBuilder<City> builder)
        {
            builder.ToTable("City");
            builder.HasKey(c => c.Id);
            builder.Property(c => c.Id).ValueGeneratedOnAdd();
            builder.Property(c => c.Name).IsRequired().HasMaxLength(100);
            builder.Property(c => c.LocalizedName).IsRequired().HasMaxLength(100);

            builder.HasData(
                new City(1, "Abakan", "Абакан"),
                new City(2, "Adygeysk", "Адыгейск"),
                new City(3, "Alchevsk", "Алчевск"),
                new City(4, "Amursk", "Амурск"),
                new City(5, "Anadyr", "Анадырь"),
                new City(6, "Angarsk", "Ангарск"),
                new City(7, "Apatity", "Апатиты"),
                new City(8, "Arzamas", "Арзамас"),
                new City(9, "Arkhangelsk", "Архангельск"),
                new City(10, "Astrakhan", "Астрахань"),
                new City(11, "Akhtubinsk", "Ахтубинск"),
                new City(12, "Achinsk", "Ачинск"),
                new City(13, "Baksan", "Баксан"),
                new City(14, "Balakovo", "Балаково"),
                new City(15, "Balashikha", "Балашиха"),
                new City(16, "Barnaul", "Барнаул"),
                new City(17, "Belgorod", "Белгород"),
                new City(18, "Belogorsk", "Белогорск"),
                new City(19, "Berdsk", "Бердск"),
                new City(20, "Berdyansk", "Бердянск"),
                new City(21, "Berezniki", "Березники"),
                new City(22, "Biysk", "Бийск"),
                new City(23, "Birobidzhan", "Биробиджан"),
                new City(24, "Blagoveshchensk", "Благовещенск"),
                new City(25, "Bor", "Бор"),
                new City(26, "Borisoglebsk", "Борисоглебск"),
                new City(27, "Borovichi", "Боровичи"),
                new City(28, "Bratsk", "Братск"),
                new City(29, "Bryansk", "Брянск"),
                new City(30, "Buy", "Буй"),
                new City(31, "Velikiye Luki", "Великие Луки"),
                new City(32, "Veliky Novgorod", "Великий Новгород"),
                new City(33, "Vilyuchinsk", "Вилючинск"),
                new City(34, "Vladivostok", "Владивосток"),
                new City(35, "Vladikavkaz", "Владикавказ"),
                new City(36, "Vladimir", "Владимир"),
                new City(37, "Volgograd", "Волгоград"),
                new City(38, "Volzhsk", "Волжск"),
                new City(39, "Volzhsky", "Волжский"),
                new City(40, "Vologda", "Вологда"),
                new City(41, "Vorkuta", "Воркута"),
                new City(42, "Voronezh", "Воронеж"),
                new City(43, "Votkinsk", "Воткинск"),
                new City(44, "Vyborg", "Выборг"),
                new City(45, "Vyshny Volochyok", "Вышний Волочёк"),
                new City(46, "Vyatskiye Polyany", "Вятские Поляны"),
                new City(47, "Vyazma", "Вязьма"),
                new City(48, "Gatchina", "Гатчина"),
                new City(49, "Gorlovka", "Горловка"),
                new City(50, "Gorno-Altaysk", "Горно-Алтайск"),
                new City(51, "Grozny", "Грозный"),
                new City(52, "Gubkin", "Губкин"),
                new City(53, "Gusinoozyorsk", "Гусиноозёрск"),
                new City(54, "Derbent", "Дербент"),
                new City(55, "Dzerzhinsk", "Дзержинск"),
                new City(56, "Dimitrovgrad", "Димитровград"),
                new City(57, "Donetsk", "Донецк"),
                new City(58, "Donskoy", "Донской"),
                new City(59, "Yevpatoria", "Евпатория"),
                new City(60, "Yekaterinburg", "Екатеринбург"),
                new City(61, "Yelets", "Елец"),
                new City(62, "Yelizovo", "Елизово"),
                new City(63, "Zheleznogorsk", "Железногорск"),
                new City(64, "Zarechny", "Заречный"),
                new City(65, "Zlatoust", "Златоуст"),
                new City(66, "Ivanovo", "Иваново"),
                new City(67, "Izhevsk", "Ижевск"),
                new City(68, "Irkutsk", "Иркутск"),
                new City(69, "Iskitim", "Искитим"),
                new City(70, "Ishim", "Ишим"),
                new City(71, "Yoshkar-Ola", "Йошкар-Ола"),
                new City(72, "Kazan", "Казань"),
                new City(73, "Kaliningrad", "Калининград"),
                new City(74, "Kaluga", "Калуга"),
                new City(75, "Kamensk-Uralsky", "Каменск-Уральский"),
                new City(76, "Kamyshin", "Камышин"),
                new City(77, "Karachayevsk", "Карачаевск"),
                new City(78, "Kasimov", "Касимов"),
                new City(79, "Kemerovo", "Кемерово"),
                new City(80, "Kerch", "Керчь"),
                new City(81, "Kineshma", "Кинешма"),
                new City(82, "Kirov", "Киров"),
                new City(83, "Kirovo-Chepetsk", "Кирово-Чепецк"),
                new City(84, "Kislovodsk", "Кисловодск"),
                new City(85, "Klintsy", "Клинцы"),
                new City(86, "Kovrov", "Ковров"),
                new City(87, "Komsomolsk-na-Amure", "Комсомольск-на-Амуре"),
                new City(88, "Kondopoga", "Кондопога"),
                new City(89, "Korsakov", "Корсаков"),
                new City(90, "Kostomuksha", "Костомукша"),
                new City(91, "Kostroma", "Кострома"),
                new City(92, "Kotlas", "Котлас"),
                new City(93, "Krasnodar", "Краснодар"),
                new City(94, "Krasnodon", "Краснодон"),
                new City(95, "Krasnokamensk", "Краснокаменск"),
                new City(96, "Krasnoyarsk", "Красноярск"),
                new City(97, "Kuznetsk", "Кузнецк"),
                new City(98, "Kurgan", "Курган"),
                new City(99, "Kursk", "Курск"),
                new City(100, "Kurchatov", "Курчатов"),
                new City(101, "Kyzyl", "Кызыл"),
                new City(102, "Livny", "Ливны"),
                new City(103, "Lipetsk", "Липецк"),
                new City(104, "Lugansk", "Луганск"),
                new City(105, "Lyudinovo", "Людиново"),
                new City(106, "Magadan", "Магадан"),
                new City(107, "Magas", "Магас"),
                new City(108, "Magnitogorsk", "Магнитогорск"),
                new City(109, "Maykop", "Майкоп"),
                new City(110, "Makeyevka", "Макеевка"),
                new City(111, "Malgobek", "Малгобек"),
                new City(112, "Makhachkala", "Махачкала"),
                new City(113, "Melitopol", "Мелитополь"),
                new City(114, "Mirny", "Мирный"),
                new City(115, "Michurinsk", "Мичуринск"),
                new City(116, "Mozdok", "Моздок"),
                new City(117, "Moscow", "Москва"),
                new City(118, "Murmansk", "Мурманск"),
                new City(119, "Murom", "Муром"),
                new City(120, "Mtsensk", "Мценск"),
                new City(121, "Naberezhnye Chelny", "Набережные Челны"),
                new City(122, "Nalchik", "Нальчик"),
                new City(123, "Naryan-Mar", "Нарьян-Мар"),
                new City(124, "Nakhodka", "Находка"),
                new City(125, "Neryungri", "Нерюнгри"),
                new City(126, "Nizhnevartovsk", "Нижневартовск"),
                new City(127, "Nizhnekamsk", "Нижнекамск"),
                new City(128, "Nizhny Novgorod", "Нижний Новгород"),
                new City(129, "Nizhny Tagil", "Нижний Тагил"),
                new City(130, "Novaya Kakhovka", "Новая Каховка"),
                new City(131, "Novozybkov", "Новозыбков"),
                new City(132, "Novokuznetsk", "Новокузнецк"),
                new City(133, "Novomoskovsk", "Новомосковск"),
                new City(134, "Novorossiysk", "Новороссийск"),
                new City(135, "Novosibirsk", "Новосибирск"),
                new City(136, "Novotroitsk", "Новотроицк"),
                new City(137, "Novocheboksarsk", "Новочебоксарск"),
                new City(138, "Novy Urengoy", "Новый Уренгой"),
                new City(139, "Norilsk", "Норильск"),
                new City(140, "Noyabrsk", "Ноябрьск"),
                new City(141, "Obninsk", "Обнинск"),
                new City(142, "Omsk", "Омск"),
                new City(143, "Oryol", "Орёл"),
                new City(144, "Orenburg", "Оренбург"),
                new City(145, "Orsk", "Орск"),
                new City(146, "Penza", "Пенза"),
                new City(147, "Pereslavl-Zalessky", "Переславль-Залесский"),
                new City(148, "Perm", "Пермь"),
                new City(149, "Petrozavodsk", "Петрозаводск"),
                new City(150, "Petropavlovsk-Kamchatsky", "Петропавловск-Камчатский"),
                new City(151, "Podolsk", "Подольск"),
                new City(152, "Prokopyevsk", "Прокопьевск"),
                new City(153, "Prokhladny", "Прохладный"),
                new City(154, "Pskov", "Псков"),
                new City(155, "Pyatigorsk", "Пятигорск"),
                new City(156, "Rasskazovo", "Рассказово"),
                new City(157, "Rzhev", "Ржев"),
                new City(158, "Roslavl", "Рославль"),
                new City(159, "Rossosh", "Россошь"),
                new City(160, "Rostov-na-Donu", "Ростов-на-Дону"),
                new City(161, "Rubtsovsk", "Рубцовск"),
                new City(162, "Ruzaevka", "Рузаевка"),
                new City(163, "Rybinsk", "Рыбинск"),
                new City(164, "Ryazan", "Рязань"),
                new City(165, "Salavat", "Салават"),
                new City(166, "Salekhard", "Салехард"),
                new City(167, "Samara", "Самара"),
                new City(168, "Saint Petersburg", "Санкт-Петербург"),
                new City(169, "Saransk", "Саранск"),
                new City(170, "Sarapul", "Сарапул"),
                new City(171, "Saratov", "Саратов"),
                new City(172, "Svobodny", "Свободный"),
                new City(173, "Severobaykalsk", "Северобайкальск"),
                new City(174, "Severodvinsk", "Северодвинск"),
                new City(175, "Severomorsk", "Североморск"),
                new City(176, "Seversk", "Северск"),
                new City(177, "Sevastopol", "Севастополь"),
                new City(178, "Simferopol", "Симферополь"),
                new City(179, "Skopin", "Скопин"),
                new City(180, "Smolensk", "Смоленск"),
                new City(181, "Sovetsk", "Советск"),
                new City(182, "Solikamsk", "Соликамск"),
                new City(183, "Sosnovy Bor", "Сосновый Бор"),
                new City(184, "Sochi", "Сочи"),
                new City(185, "Stavropol", "Ставрополь"),
                new City(186, "Staraya Russa", "Старая Русса"),
                new City(187, "Stary Oskol", "Старый Оскол"),
                new City(188, "Sterlitamak", "Стерлитамак"),
                new City(189, "Strezhevoy", "Стрежевой"),
                new City(190, "Surgut", "Сургут"),
                new City(191, "Syzran", "Сызрань"),
                new City(192, "Syktyvkar", "Сыктывкар"),
                new City(193, "Taganrog", "Таганрог"),
                new City(194, "Tambov", "Тамбов"),
                new City(195, "Tara", "Тара"),
                new City(196, "Tver", "Тверь"),
                new City(197, "Tobolsk", "Тобольск"),
                new City(198, "Tolyatti", "Тольятти"),
                new City(199, "Tomsk", "Томск"),
                new City(200, "Tula", "Тула"),
                new City(201, "Tyumen", "Тюмень"),
                new City(202, "Ulan-Ude", "Улан-Удэ"),
                new City(203, "Ulyanovsk", "Ульяновск"),
                new City(204, "Urus-Martan", "Урус-Мартан"),
                new City(205, "Ussuriysk", "Уссурийск"),
                new City(206, "Ufa", "Уфа"),
                new City(207, "Ukhta", "Ухта"),
                new City(208, "Khabarovsk", "Хабаровск"),
                new City(209, "Khanty-Mansiysk", "Ханты-Мансийск"),
                new City(210, "Khasavyurt", "Хасавюрт"),
                new City(211, "Kherson", "Херсон"),
                new City(212, "Khimki", "Химки"),
                new City(213, "Kholmsk", "Холмск"),
                new City(214, "Cheboksary", "Чебоксары"),
                new City(215, "Chelyabinsk", "Челябинск"),
                new City(216, "Cherepovets", "Череповец"),
                new City(217, "Cherkessk", "Черкесск"),
                new City(218, "Chernogorsk", "Черногорск"),
                new City(219, "Chernyakhovsk", "Черняховск"),
                new City(220, "Chita", "Чита"),
                new City(221, "Shadrinsk", "Шадринск"),
                new City(222, "Shali", "Шали"),
                new City(223, "Sharya", "Шарья"),
                new City(224, "Shakhty", "Шахты"),
                new City(225, "Shuya", "Шуя"),
                new City(226, "Elista", "Элиста"),
                new City(227, "Engels", "Энгельс"),
                new City(228, "Yuzhno-Sakhalinsk", "Южно-Сахалинск"),
                new City(229, "Yakutsk", "Якутск"),
                new City(230, "Yalta", "Ялта"),
                new City(231, "Yaroslavl", "Ярославль")
            );
        }
    }
}